"""Post-train step: hard splat cap, held-out eval and PLY export in one load.

Runs inside the CUDA container after ``ns-train``; replaces the separate
``ns-export gaussian-splat`` + ``ns-eval`` calls (each re-loaded the model and
the images, and nerfstudio's exporter writes the PLY one value at a time, ~30 s
for ~0.5 M splats). One ``eval_setup`` load, then:

1. **Hard cap**: if the model has more than ``--budget`` splats, keep the
   ``budget`` most important and drop the rest. Importance is each splat's
   rendered contribution: its blending weight summed over every training view
   (from one render + backward pass per view, ~10 s for 272 views); without
   cameras it falls back to ``splat_ops.importance`` (alpha x largest
   cross-section). This is the guarantee behind
   ``ReconstructionConfig.splat_budget``; ``ns_train_capped`` limits growth
   during training, which is the path that keeps quality (a large prune after
   training, with no fine-tuning, costs far more PSNR: spike report).
2. **Eval** (``--eval``): PSNR / SSIM / LPIPS over the held-out views of the
   *capped* model (what ships), renders written to ``--renders``.
3. **Export**: nerfstudio's ``ExportGaussianSplat`` PLY layout (same fields,
   order, NaN/Inf filter and 1/255-opacity filter), written vectorized.

Writes ``finish.json`` (counts, metrics, timings) next to the PLY. torch /
numpy / nerfstudio are imported only in ``main`` (CI imports the package
without them).
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

LOW_OPACITY_LOGIT = -5.5373  # logit(1/255): gsplat skips these when rasterizing


def ply_fields(sh_rest_count: int) -> list[str]:
    """Vertex property order of nerfstudio 1.1.5's gaussian-splat PLY export."""
    fields = ["x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2"]
    fields += [f"f_rest_{i}" for i in range(sh_rest_count)]
    fields += ["opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3"]
    return fields


def ply_header(count: int, fields: list[str], version: str) -> bytes:
    lines = [
        "ply",
        "format binary_little_endian 1.0",
        f"comment Generated by Nerstudio {version}",
        "comment Vertical Axis: z",
        f"element vertex {count}",
        *[f"property float {name}" for name in fields],
        "end_header",
    ]
    return ("\n".join(lines) + "\n").encode()


def contribution_scores(model, cameras):
    """Per-splat blending weight summed over ``cameras`` (render + backward).

    d(sum of rendered alpha)/d(opacity logit) is each splat's summed
    transmittance-weighted footprint times sigmoid'(logit); dividing by
    sigmoid' and multiplying by alpha gives its blending weight, i.e. how much
    of the images it actually paints.
    """
    import torch

    params = model.gauss_params
    for name, param in params.items():
        param.requires_grad_(name == "opacities")
    opacities = params["opacities"]
    total = torch.zeros(opacities.shape[0], device=opacities.device)
    model.eval()
    for i in range(len(cameras)):
        opacities.grad = None
        with torch.enable_grad():
            out = model.get_outputs(cameras[i : i + 1].to(opacities.device))
            out["accumulation"].sum().backward()
        if opacities.grad is not None:
            total += opacities.grad.detach().abs().reshape(-1)
    alpha = torch.sigmoid(opacities.detach().reshape(-1))
    return total / (alpha * (1 - alpha)).clamp_min(1e-12) * alpha


def static_scores(model):
    """``splat_ops.importance`` vectorized: alpha x area of the two largest axes."""
    import torch

    top2 = torch.topk(model.scales, 2, dim=-1).values.sum(dim=-1)
    return torch.sigmoid(model.opacities.reshape(-1)) * torch.exp(top2)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="reconstruction.ns_finish")
    parser.add_argument("--load-config", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--budget", type=int, required=True)
    parser.add_argument("--eval", action="store_true")
    parser.add_argument("--renders", type=Path, default=None)
    args = parser.parse_args(argv)

    from importlib.metadata import version

    import numpy as np
    import torch
    from nerfstudio.utils.eval_utils import eval_setup

    report: dict = {"budget": args.budget}
    started = time.monotonic()
    _, pipeline, _, _ = eval_setup(args.load_config, test_mode="test" if args.eval else "inference")
    model = pipeline.model
    report["load_s"] = round(time.monotonic() - started, 2)

    # 1. Hard cap by importance.
    started = time.monotonic()
    with torch.no_grad():
        count = int(model.means.shape[0])
        report["trained_splats"] = count
        if count > args.budget:
            cameras = getattr(getattr(pipeline.datamanager, "train_dataset", None), "cameras", None)
            if cameras is not None and len(cameras) > 0:
                score = contribution_scores(model, cameras)
                report["cap_score"] = f"contribution ({len(cameras)} views)"
            else:
                score = static_scores(model)
                report["cap_score"] = "static"
            keep = torch.topk(score, args.budget).indices.sort().values
            for name, param in list(model.gauss_params.items()):
                model.gauss_params[name] = torch.nn.Parameter(param.detach()[keep].contiguous())
        report["capped_splats"] = int(model.means.shape[0])
        report["cap_applied"] = count > args.budget
    report["cap_s"] = round(time.monotonic() - started, 2)

    # 2. Held-out eval of the model that ships.
    if args.eval:
        started = time.monotonic()
        metrics = pipeline.get_average_eval_image_metrics(output_path=args.renders, get_std=True)
        report["eval_s"] = round(time.monotonic() - started, 2)
        report["results"] = {k: float(v) for k, v in metrics.items()}
        report["eval_views"] = len(pipeline.datamanager.fixed_indices_eval_dataloader)

    # 3. PLY export (nerfstudio ExportGaussianSplat layout, vectorized).
    started = time.monotonic()
    with torch.no_grad():
        n = int(model.means.shape[0])
        rest = model.shs_rest.transpose(1, 2).contiguous().reshape(n, -1)
        cols = [
            model.means,
            torch.zeros((n, 3), device=model.means.device),
            model.shs_0.contiguous().reshape(n, -1),
            rest,
            model.opacities.reshape(n, 1),
            model.scales,
            model.quats,
        ]
        data = torch.cat([c.float() for c in cols], dim=1).cpu().numpy()
    fields = ply_fields(rest.shape[1])
    finite = np.isfinite(data).all(axis=1)
    opaque = data[:, fields.index("opacity")] >= LOW_OPACITY_LOGIT
    data = np.ascontiguousarray(data[finite & opaque], dtype="<f4")
    report["nonfinite_dropped"] = int((~finite).sum())
    report["low_opacity_dropped"] = int((finite & ~opaque).sum())
    report["exported_splats"] = int(data.shape[0])
    args.output_dir.mkdir(parents=True, exist_ok=True)
    ply = args.output_dir / "splat.ply"
    with ply.open("wb") as fh:
        fh.write(ply_header(data.shape[0], fields, version("nerfstudio")))
        fh.write(data.tobytes())
    report["export_s"] = round(time.monotonic() - started, 2)
    (args.output_dir / "finish.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps({k: v for k, v in report.items() if k != "results"}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
