using System;
using System.IO;
using System.Reflection;
using System.Text;
using GaussianSplatting.Editor;
using GaussianSplatting.Runtime;
using GiganticJourneys.Splats;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using Random = System.Random;

namespace GiganticJourneys.EditorTools.Splats
{
    /// <summary>
    /// The M0-UNITY-02 sample splat and sample scene.
    ///
    /// The sample is generated procedurally (a small summit: terrain, trees and a flag
    /// on the peak), so it contains no captured imagery, no faces, no documents and no
    /// third-party data. The generated PLY is written to <c>Temp/</c> only (the repo never
    /// tracks .ply/.spz, see the repo hygiene check); what is committed is the
    /// renderer's converted GaussianSplatAsset under <see cref="Folder"/>. Generation
    /// is seeded and deterministic, so re-importing reproduces the committed bytes.
    ///
    /// Batchmode: <c>-executeMethod GiganticJourneys.EditorTools.Splats.SampleSplat.Run</c>
    /// (rebuilds the asset, the settings asset and, if missing, the scene).
    /// </summary>
    public static class SampleSplat
    {
        public const string Folder = "Assets/Capture/Samples";
        public const string SampleName = "gj_sample_summit";
        public const string AssetPath = Folder + "/" + SampleName + ".asset";
        public const string ScenePath = Folder + "/SplatSample.unity";
        public const string SettingsPath = "Assets/Settings/SplatRenderSettings.asset";
        public const string PlyPath = "Temp/GJSampleSplat/" + SampleName + ".ply";
        public const int Seed = 20260927;
        public const string Source =
            "procedural (self-generated by SampleSplat.cs, seed 20260927; no captured imagery)";

        // Renderer shader + compute GUIDs (package MonoImporter default references).
        const string ShaderSplatsGuid = "ed800126ae8844a67aad1974ddddd59c";
        const string ShaderCompositeGuid = "7e184af7d01193a408eb916d8acafff9"; // package composite (replaced)
        public const string AlphaSafeCompositePath =
            "Assets/GiganticJourneys/Splats/Shaders/GJSplatCompositeSafe.shader";
        const string ShaderDebugPointsGuid = "b44409fc67214394f8f47e4e2648425e";
        const string ShaderDebugBoxesGuid = "4006f2680fd7c8b4cbcb881454c782be";
        const string CsSplatUtilitiesGuid = "ec84f78b836bd4f96a105d6b804f08bd";

        const float SH0 = 0.2820948f;

        [MenuItem("Gigantic Journeys/Splats/Rebuild Sample Splat + Scene")]
        public static void Rebuild()
        {
            ImportSample();
            EnsureSettings();
            EnsureScene(force: false);
        }

        /// <summary>Batchmode entry point; exits non-zero on failure.</summary>
        public static void Run()
        {
            var code = 0;
            try
            {
                Rebuild();
            }
            catch (Exception e)
            {
                Debug.LogException(e);
                code = 1;
            }
            EditorApplication.Exit(code);
        }

        /// <summary>Generates the PLY into Temp/ and converts it into the committed asset.</summary>
        public static GaussianSplatAsset ImportSample()
        {
            var count = WritePly(PlyPath);
            var asset = ConvertPly(PlyPath, Folder);
            if (asset == null || asset.splatCount != count)
                throw new InvalidOperationException(
                    $"sample splat import produced {(asset == null ? "no asset" : asset.splatCount + " splats")}, expected {count}"
                );
            return asset;
        }

        /// <summary>Runs the renderer's own PLY/SPZ converter (its Editor window) headlessly.</summary>
        /// <paramref name="lossless"/> stores everything as float32 (diagnostics only: isolates
        /// the package quantization from the shader when scoring the Unity path).
        public static GaussianSplatAsset ConvertPly(
            string plyPath,
            string outputFolder,
            bool lossless = false
        )
        {
            var creator = ScriptableObject.CreateInstance<GaussianSplatAssetCreator>();
            try
            {
                const BindingFlags flags = BindingFlags.Instance | BindingFlags.NonPublic;
                var type = typeof(GaussianSplatAssetCreator);
                void Set(string field, object value) =>
                    (
                        type.GetField(field, flags)
                        ?? throw new MissingFieldException(type.Name, field)
                    ).SetValue(creator, value);
                Set("m_InputFile", Path.GetFullPath(plyPath));
                Set("m_ImportCameras", false);
                Set("m_OutputFolder", outputFolder);
                // "Medium" quality without SH clustering (clustering is randomized; this keeps
                // the output deterministic and the sample has no view-dependent colour anyway).
                Set(
                    "m_FormatPos",
                    lossless
                        ? GaussianSplatAsset.VectorFormat.Float32
                        : GaussianSplatAsset.VectorFormat.Norm11
                );
                Set(
                    "m_FormatScale",
                    lossless
                        ? GaussianSplatAsset.VectorFormat.Float32
                        : GaussianSplatAsset.VectorFormat.Norm11
                );
                Set(
                    "m_FormatColor",
                    lossless
                        ? GaussianSplatAsset.ColorFormat.Float32x4
                        : GaussianSplatAsset.ColorFormat.Norm8x4
                );
                Set(
                    "m_FormatSH",
                    lossless
                        ? GaussianSplatAsset.SHFormat.Float32
                        : GaussianSplatAsset.SHFormat.Norm6
                );
                (
                    type.GetMethod("CreateAsset", flags)
                    ?? throw new MissingMethodException(type.Name, "CreateAsset")
                ).Invoke(creator, null);
                var error = type.GetField("m_ErrorMessage", flags)?.GetValue(creator) as string;
                if (!string.IsNullOrEmpty(error))
                    throw new InvalidOperationException("splat conversion failed: " + error);
            }
            finally
            {
                UnityEngine.Object.DestroyImmediate(creator);
            }
            var name = Path.GetFileNameWithoutExtension(plyPath);
            var asset = AssetDatabase.LoadAssetAtPath<GaussianSplatAsset>(
                $"{outputFolder}/{name}.asset"
            );
            if (asset != null)
                SetContentHash(asset);
            return asset;
        }

        /// <summary>
        /// Replaces the converter's data hash with a hash of the data files' contents. Upstream
        /// hashes the chunk NativeArray handle (a memory address) rather than its contents, so
        /// its hash changes on every conversion even when the bytes are identical. The renderer
        /// only uses the hash to notice changed data, which a content hash serves exactly.
        /// </summary>
        public static void SetContentHash(GaussianSplatAsset asset)
        {
            var hash = new Hash128((uint)asset.splatCount, (uint)asset.formatVersion, 0, 0);
            var files = new[]
            {
                asset.chunkData,
                asset.posData,
                asset.otherData,
                asset.colorData,
                asset.shData,
            };
            foreach (var data in files)
            {
                if (data != null)
                    hash.Append(data.bytes);
            }
            if (asset.dataHash == hash)
                return;
            asset.SetDataHash(hash);
            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
        }

        /// <summary>Creates the single LOD/culling settings asset if it does not exist.</summary>
        public static SplatRenderSettings EnsureSettings()
        {
            var settings = AssetDatabase.LoadAssetAtPath<SplatRenderSettings>(SettingsPath);
            if (settings != null)
                return settings;
            settings = ScriptableObject.CreateInstance<SplatRenderSettings>();
            AssetDatabase.CreateAsset(settings, SettingsPath);
            AssetDatabase.SaveAssets();
            return settings;
        }

        /// <summary>Creates Assets/Capture/Samples/SplatSample.unity (only when missing unless forced).</summary>
        public static void EnsureScene(bool force)
        {
            if (!force && File.Exists(ScenePath))
                return;
            var asset =
                AssetDatabase.LoadAssetAtPath<GaussianSplatAsset>(AssetPath) ?? ImportSample();
            var settings = EnsureSettings();

            var scene = EditorSceneManager.NewScene(
                NewSceneSetup.DefaultGameObjects,
                NewSceneMode.Single
            );
            var cam = Camera.main;
            cam.transform.SetPositionAndRotation(
                new Vector3(0f, 2.6f, -6.2f),
                Quaternion.LookRotation(new Vector3(0f, 0.75f, 0f) - new Vector3(0f, 2.6f, -6.2f))
            );
            cam.nearClipPlane = 0.05f;
            cam.farClipPlane = 200f;
            cam.fieldOfView = 45f;

            var go = new GameObject("SampleSplat");
            var renderer = go.AddComponent<GaussianSplatRenderer>();
            AssignRendererResources(renderer);
            renderer.m_Asset = asset;
            var applier = go.AddComponent<SplatRenderSettingsApplier>();
            applier.settings = settings;

            EditorSceneManager.SaveScene(scene, ScenePath);
            AssetDatabase.SaveAssets();
        }

        /// <summary>Sets the renderer's shader and compute references explicitly.</summary>
        public static void AssignRendererResources(GaussianSplatRenderer r)
        {
            r.m_ShaderSplats = Load<Shader>(ShaderSplatsGuid);
            // GJ's alpha-safe composite instead of the package's (NaN -> black opaque objects on Metal).
            r.m_ShaderComposite =
                AssetDatabase.LoadAssetAtPath<Shader>(AlphaSafeCompositePath)
                ?? throw new InvalidOperationException($"{AlphaSafeCompositePath} not found");
            r.m_ShaderDebugPoints = Load<Shader>(ShaderDebugPointsGuid);
            r.m_ShaderDebugBoxes = Load<Shader>(ShaderDebugBoxesGuid);
            r.m_CSSplatUtilities = Load<ComputeShader>(CsSplatUtilitiesGuid);
        }

        static T Load<T>(string guid)
            where T : UnityEngine.Object
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            return AssetDatabase.LoadAssetAtPath<T>(path)
                ?? throw new InvalidOperationException(
                    $"renderer resource {guid} ({typeof(T).Name}) not found; is the package installed?"
                );
        }

        // ---------------------------------------------------------------- generation

        struct Splat
        {
            public Vector3 Pos;
            public Color Col;
            public float Opacity;
            public Vector3 Scale;
            public Quaternion Rot;
        }

        static float Height(float x, float z)
        {
            var peak = 1.9f * Mathf.Exp(-(x * x + z * z) / (2f * 0.85f * 0.85f));
            var dx = x - 1.35f;
            var dz = z + 0.55f;
            var shoulder = 0.55f * Mathf.Exp(-(dx * dx + dz * dz) / (2f * 0.5f * 0.5f));
            var ridges =
                0.06f * Mathf.Sin(3.1f * x + 1.7f * z) * Mathf.Cos(2.3f * z - 0.9f * x)
                + 0.03f * Mathf.Sin(7.3f * x - 5.1f * z);
            return peak + shoulder + ridges * Mathf.Clamp01(peak + shoulder);
        }

        static Vector3 Normal(float x, float z)
        {
            const float e = 0.01f;
            var hx = (Height(x + e, z) - Height(x - e, z)) / (2f * e);
            var hz = (Height(x, z + e) - Height(x, z - e)) / (2f * e);
            return new Vector3(-hx, 1f, -hz).normalized;
        }

        static Color TerrainColor(float h, float slope, float n)
        {
            var grass = new Color(0.30f, 0.50f, 0.22f);
            var meadow = new Color(0.52f, 0.60f, 0.28f);
            var rock = new Color(0.47f, 0.42f, 0.38f);
            var snow = new Color(0.94f, 0.95f, 0.98f);
            var c = Color.Lerp(grass, meadow, Mathf.Clamp01(n));
            c = Color.Lerp(c, rock, Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(0.55f, 1.1f, h)));
            c = Color.Lerp(
                c,
                rock,
                Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(0.45f, 0.8f, slope))
            );
            var snowline = 1.38f + 0.08f * n;
            c = Color.Lerp(
                c,
                snow,
                Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(snowline, snowline + 0.15f, h))
            );
            return c;
        }

        static Splat Make(
            Vector3 pos,
            Color col,
            Vector3 scale,
            Quaternion rot,
            float opacity = 0.97f
        ) =>
            new Splat
            {
                Pos = pos,
                Col = col,
                Opacity = opacity,
                Scale = scale,
                Rot = rot,
            };

        static Color Jitter(Random rng, Color c, float amount)
        {
            var k = 1f + ((float)rng.NextDouble() * 2f - 1f) * amount;
            return new Color(
                Mathf.Clamp01(c.r * k),
                Mathf.Clamp01(c.g * k),
                Mathf.Clamp01(c.b * k)
            );
        }

        static float Range(Random rng, float a, float b) => a + (float)rng.NextDouble() * (b - a);

        /// <summary>Writes the procedural summit as a binary little-endian 3DGS PLY; returns the splat count.</summary>
        public static int WritePly(string path)
        {
            var rng = new Random(Seed);
            var splats = new System.Collections.Generic.List<Splat>(48000);

            // Terrain: a jittered grid over a 3 m radius disc, splats flattened onto the surface.
            const float radius = 3f;
            const int grid = 190;
            const float step = 2f * radius / grid;
            for (var i = 0; i < grid; i++)
            for (var j = 0; j < grid; j++)
            {
                var x = -radius + (i + Range(rng, 0.1f, 0.9f)) * step;
                var z = -radius + (j + Range(rng, 0.1f, 0.9f)) * step;
                var r = Mathf.Sqrt(x * x + z * z);
                if (r > radius)
                    continue;
                var h = Height(x, z);
                var n = Normal(x, z);
                var slope = 1f - n.y;
                var noise = 0.5f + 0.5f * Mathf.Sin(5.3f * x) * Mathf.Cos(4.7f * z);
                var col = Jitter(rng, TerrainColor(h, slope, noise), 0.06f);
                var edge = Mathf.Clamp01((radius - r) / 0.25f);
                var s = step * 0.75f;
                splats.Add(
                    Make(
                        new Vector3(x, h, z),
                        col,
                        new Vector3(s, s * 0.25f, s),
                        Quaternion.FromToRotation(Vector3.up, n),
                        0.97f * edge + 0.02f
                    )
                );
            }

            // Trees: small cones on the lower slopes.
            var trunk = new Color(0.33f, 0.22f, 0.13f);
            var needles = new Color(0.12f, 0.30f, 0.14f);
            for (var t = 0; t < 26; t++)
            {
                var ang = Range(rng, 0f, 2f * Mathf.PI);
                var rad = Range(rng, 1.45f, 2.7f);
                var bx = Mathf.Cos(ang) * rad;
                var bz = Mathf.Sin(ang) * rad;
                var by = Height(bx, bz);
                if (by > 0.9f)
                    continue;
                var height = Range(rng, 0.28f, 0.45f);
                for (var k = 0; k < 20; k++)
                    splats.Add(
                        Make(
                            new Vector3(bx, by + k * 0.006f, bz),
                            trunk,
                            new Vector3(0.012f, 0.012f, 0.012f),
                            Quaternion.identity
                        )
                    );
                for (var k = 0; k < 360; k++)
                {
                    var v = Range(rng, 0.12f, 1f);
                    var cr = (1f - v) * height * 0.35f * Mathf.Sqrt((float)rng.NextDouble());
                    var ca = Range(rng, 0f, 2f * Mathf.PI);
                    splats.Add(
                        Make(
                            new Vector3(
                                bx + Mathf.Cos(ca) * cr,
                                by + v * height,
                                bz + Mathf.Sin(ca) * cr
                            ),
                            Jitter(rng, needles, 0.18f),
                            Vector3.one * 0.018f,
                            Quaternion.identity
                        )
                    );
                }
            }

            // Summit flag: a pole and a red pennant on the peak.
            var top = new Vector3(0f, Height(0f, 0f), 0f);
            for (var k = 0; k < 60; k++)
                splats.Add(
                    Make(
                        top + new Vector3(0f, k * 0.006f, 0f),
                        new Color(0.85f, 0.85f, 0.82f),
                        Vector3.one * 0.006f,
                        Quaternion.identity
                    )
                );
            for (var u = 0; u < 16; u++)
            for (var v = 0; v < 10; v++)
            {
                var fu = u / 15f;
                splats.Add(
                    Make(
                        top
                            + new Vector3(
                                0.012f + fu * 0.17f,
                                0.36f - v * 0.011f * (1f - 0.5f * fu) - fu * 0.02f,
                                0.012f * Mathf.Sin(fu * 6f)
                            ),
                        new Color(0.86f, 0.12f, 0.10f),
                        new Vector3(0.008f, 0.008f, 0.004f),
                        Quaternion.identity
                    )
                );
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");
            string[] props =
            {
                "x",
                "y",
                "z",
                "f_dc_0",
                "f_dc_1",
                "f_dc_2",
                "opacity",
                "scale_0",
                "scale_1",
                "scale_2",
                "rot_0",
                "rot_1",
                "rot_2",
                "rot_3",
            };
            var header = new StringBuilder();
            header.Append("ply\nformat binary_little_endian 1.0\n");
            header.Append($"element vertex {splats.Count}\n");
            foreach (var p in props)
                header.Append($"property float {p}\n");
            header.Append("end_header\n");
            using var fs = new FileStream(path, FileMode.Create, FileAccess.Write);
            using var w = new BinaryWriter(fs);
            w.Write(Encoding.ASCII.GetBytes(header.ToString()));
            foreach (var s in splats)
            {
                w.Write(s.Pos.x);
                w.Write(s.Pos.y);
                w.Write(s.Pos.z);
                w.Write((s.Col.r - 0.5f) / SH0);
                w.Write((s.Col.g - 0.5f) / SH0);
                w.Write((s.Col.b - 0.5f) / SH0);
                var o = Mathf.Clamp(s.Opacity, 0.001f, 0.999f);
                w.Write(Mathf.Log(o / (1f - o)));
                w.Write(Mathf.Log(s.Scale.x));
                w.Write(Mathf.Log(s.Scale.y));
                w.Write(Mathf.Log(s.Scale.z));
                w.Write(s.Rot.w);
                w.Write(s.Rot.x);
                w.Write(s.Rot.y);
                w.Write(s.Rot.z);
            }
            return splats.Count;
        }
    }
}
